print("Getting to know you!")
myName = input("You are")
print()
myFood= input("what is your favorite food?")
print()
myMusic= input("What music do you listen to?")
print()
print(" So your name is")
print(myName)
print()
print("You like to eat")
print(myFood)
print()
print("and you love to listen to")
print(myMusic)
print()
print(" You seem like a great person and we'd love to get to know you better.")